In [99]:
# TensorFlow and tf.keras
import tensorflow as tf
import numpy as np
from tensorflow import keras

#tf version should be 2.5 or higher
tf.__version__


'2.8.2'

In [100]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

In [101]:
#scale model
train_images = train_images / 255.0
test_images = test_images / 255.0

In [102]:
#reshape inputs of CNN layers
train_images = train_images.reshape(train_images.shape[0], 28, 28, 1)
test_images = test_images.reshape(test_images.shape[0], 28, 28, 1)

In [103]:
#setup model
model = keras.Sequential([
    keras.layers.Conv2D(kernel_size=3, filters = 12, use_bias=False, padding='same',input_shape=(28, 28, 1)),
    keras.layers.BatchNormalization(center=True,scale=False),
    keras.layers.Activation('relu'),
    keras.layers.Conv2D(kernel_size=6, filters = 24, use_bias=False, padding='same',strides = 2),
    keras.layers.BatchNormalization(center=True,scale=False),
    keras.layers.Activation('relu'),
    keras.layers.Conv2D(kernel_size=6, filters = 48, use_bias=False, padding='same', strides = 2),
    keras.layers.BatchNormalization(center=True,scale=False),
    keras.layers.Activation('relu'),
    keras.layers.Flatten(),
    keras.layers.Dense(200, use_bias = False),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.4),
    keras.layers.Dense(60, use_bias=False),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.4),
    keras.layers.Dense(10, activation = 'softmax')
])

In [104]:
#compile model
model.compile(optimizer='adam',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [105]:
#train model
model.fit(train_images, train_labels, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 103s 55ms/step - loss: 0.2397 - accuracy: 0.9367
Epoch 2/10
1875/1875 [==============================] - 103s 55ms/step - loss: 0.0893 - accuracy: 0.9761
Epoch 3/10
1875/1875 [==============================] - 102s 55ms/step - loss: 0.0660 - accuracy: 0.9817
Epoch 4/10
1875/1875 [==============================] - 102s 55ms/step - loss: 0.0563 - accuracy: 0.9843
Epoch 5/10
1875/1875 [==============================] - 102s 54ms/step - loss: 0.0463 - accuracy: 0.9872
Epoch 6/10
1875/1875 [==============================] - 103s 55ms/step - loss: 0.0399 - accuracy: 0.9892
Epoch 7/10
1875/1875 [==============================] - 103s 55ms/step - loss: 0.0370 - accuracy: 0.9900
Epoch 8/10
1875/1875 [==============================] - 103s 55ms/step - loss: 0.0285 - accuracy: 0.9921
Epoch 9/10
1875/1875 [==============================] - 103s 55ms/step - loss: 0.0288 - accuracy: 0.9919
Epoch 10/10
1875/1875 [==============================] 

In [106]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 5s 14ms/step - loss: 0.0241 - accuracy: 0.9935

Test accuracy: 0.9934999942779541


In [107]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

In [108]:
#Raw predictions
predictions

array([[1.34107361e-11, 9.34843758e-10, 3.15019233e-10, 6.24190977e-10,
        3.26953487e-09, 8.19105950e-10, 3.03750341e-12, 1.00000000e+00,
        2.22549149e-12, 9.70081460e-10],
       [4.76543818e-08, 9.77496768e-08, 9.99999881e-01, 2.21444036e-08,
        1.70631353e-09, 1.24748434e-10, 9.76257297e-09, 4.08261380e-09,
        7.17012782e-10, 2.47637105e-10],
       [5.01918151e-09, 9.99999762e-01, 1.34762856e-09, 5.77264514e-10,
        1.47821924e-08, 8.24656621e-10, 1.53812751e-09, 1.69407983e-07,
        6.42318625e-08, 7.14639792e-10],
       [9.99940991e-01, 1.31111292e-07, 4.73643098e-07, 2.21750938e-08,
        1.28232017e-07, 1.13034908e-07, 5.59915534e-05, 3.73782640e-08,
        1.89977854e-07, 1.84141550e-06],
       [1.91389127e-09, 8.90464094e-08, 2.96804501e-08, 1.53764734e-08,
        9.99917746e-01, 1.59801075e-07, 1.18510826e-07, 4.26580762e-08,
        5.34673710e-08, 8.16692918e-05]], dtype=float32)

In [109]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4]


In [110]:
# Check our predictions against the ground truths
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]


In [110]:
Comments:
To get the accuracy of more than 99.3%, firstly, I changed the optimizer to adam, added dense layers, changed the activation to relu. 
But I couldn't get the desired output. Later, filters were added. As mentioned in the lecture slides. I added the drop out layers with 
40% between each dense layers and batch normalization, I could get the accuracy of 99.34%. 